import type { Metadata } from "next";
import { Afacad } from 'next/font/google';
import "./globals.css";
import { Header } from "./_components/header";

const lato = Afacad({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={lato.className}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
